### ISSUE TITLE
Link in README.md not working 

### ISSUE THREAD

**Issue by robgal519** [keigezellig/kanbanwarrior#1]
First link in the file does not work.
(http://keigezellig.blog.com/2013/03/07/kanban-warrior/)
` (110) Connection timed out` error was returned.

**Comment by keigezellig** [comment]
I moved my blog to somewhere else and it seems that the redirect on the url in the readme stopped working :p

**Comment by keigezellig** [comment]
Fixed this in the new 1.0.1 release
